/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as AskRouteImport } from './routes/ask'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as ChecklistRouteImport } from './routes/checklist'
import { Route as CostRouteImport } from './routes/cost'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as ItineraryRouteImport } from './routes/itinerary'
import { Route as MapRouteImport } from './routes/map'
import { Route as PlanningRouteImport } from './routes/planning'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StoryRouteImport } from './routes/story'
import { Route as TravellersRouteImport } from './routes/travellers'
import { Route as VehicleRouteImport } from './routes/vehicle'
import { Route as CostShareTokenRouteImport } from './routes/cost.share.$token'
import { Route as ApiPublicHooksBookingRemindersRouteImport } from './routes/api/public/hooks/booking-reminders'
import { Route as ApiPublicHooksDailyBadgeRouteImport } from './routes/api/public/hooks/daily-badge'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const AskRoute = AskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const ChecklistRoute = ChecklistRouteImport.update({
  id: '/checklist',
  path: '/checklist',
  getParentRoute: () => rootRouteImport,
} as any)
const CostRoute = CostRouteImport.update({
  id: '/cost',
  path: '/cost',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const ItineraryRoute = ItineraryRouteImport.update({
  id: '/itinerary',
  path: '/itinerary',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanningRoute = PlanningRouteImport.update({
  id: '/planning',
  path: '/planning',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryRoute = StoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => rootRouteImport,
} as any)
const TravellersRoute = TravellersRouteImport.update({
  id: '/travellers',
  path: '/travellers',
  getParentRoute: () => rootRouteImport,
} as any)
const VehicleRoute = VehicleRouteImport.update({
  id: '/vehicle',
  path: '/vehicle',
  getParentRoute: () => rootRouteImport,
} as any)
const CostShareTokenRoute = CostShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => CostRoute,
} as any)
const ApiPublicHooksBookingRemindersRoute =
  ApiPublicHooksBookingRemindersRouteImport.update({
    id: '/api/public/hooks/booking-reminders',
    path: '/api/public/hooks/booking-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDailyBadgeRoute =
  ApiPublicHooksDailyBadgeRouteImport.update({
    id: '/api/public/hooks/daily-badge',
    path: '/api/public/hooks/daily-badge',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/ask': typeof AskRoute
  '/bookings': typeof BookingsRoute
  '/checklist': typeof ChecklistRoute
  '/cost': typeof CostRouteWithChildren
  '/documents': typeof DocumentsRoute
  '/itinerary': typeof ItineraryRoute
  '/map': typeof MapRoute
  '/planning': typeof PlanningRoute
  '/settings': typeof SettingsRoute
  '/story': typeof StoryRoute
  '/travellers': typeof TravellersRoute
  '/vehicle': typeof VehicleRoute
  '/cost/share/$token': typeof CostShareTokenRoute
  '/api/public/hooks/booking-reminders': typeof ApiPublicHooksBookingRemindersRoute
  '/api/public/hooks/daily-badge': typeof ApiPublicHooksDailyBadgeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/ask': typeof AskRoute
  '/bookings': typeof BookingsRoute
  '/checklist': typeof ChecklistRoute
  '/cost': typeof CostRouteWithChildren
  '/documents': typeof DocumentsRoute
  '/itinerary': typeof ItineraryRoute
  '/map': typeof MapRoute
  '/planning': typeof PlanningRoute
  '/settings': typeof SettingsRoute
  '/story': typeof StoryRoute
  '/travellers': typeof TravellersRoute
  '/vehicle': typeof VehicleRoute
  '/cost/share/$token': typeof CostShareTokenRoute
  '/api/public/hooks/booking-reminders': typeof ApiPublicHooksBookingRemindersRoute
  '/api/public/hooks/daily-badge': typeof ApiPublicHooksDailyBadgeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/ask': typeof AskRoute
  '/bookings': typeof BookingsRoute
  '/checklist': typeof ChecklistRoute
  '/cost': typeof CostRouteWithChildren
  '/documents': typeof DocumentsRoute
  '/itinerary': typeof ItineraryRoute
  '/map': typeof MapRoute
  '/planning': typeof PlanningRoute
  '/settings': typeof SettingsRoute
  '/story': typeof StoryRoute
  '/travellers': typeof TravellersRoute
  '/vehicle': typeof VehicleRoute
  '/cost/share/$token': typeof CostShareTokenRoute
  '/api/public/hooks/booking-reminders': typeof ApiPublicHooksBookingRemindersRoute
  '/api/public/hooks/daily-badge': typeof ApiPublicHooksDailyBadgeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/achievements'
    | '/ask'
    | '/bookings'
    | '/checklist'
    | '/cost'
    | '/documents'
    | '/itinerary'
    | '/map'
    | '/planning'
    | '/settings'
    | '/story'
    | '/travellers'
    | '/vehicle'
    | '/cost/share/$token'
    | '/api/public/hooks/booking-reminders'
    | '/api/public/hooks/daily-badge'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/achievements'
    | '/ask'
    | '/bookings'
    | '/checklist'
    | '/cost'
    | '/documents'
    | '/itinerary'
    | '/map'
    | '/planning'
    | '/settings'
    | '/story'
    | '/travellers'
    | '/vehicle'
    | '/cost/share/$token'
    | '/api/public/hooks/booking-reminders'
    | '/api/public/hooks/daily-badge'
  id:
    | '__root__'
    | '/'
    | '/achievements'
    | '/ask'
    | '/bookings'
    | '/checklist'
    | '/cost'
    | '/documents'
    | '/itinerary'
    | '/map'
    | '/planning'
    | '/settings'
    | '/story'
    | '/travellers'
    | '/vehicle'
    | '/cost/share/$token'
    | '/api/public/hooks/booking-reminders'
    | '/api/public/hooks/daily-badge'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AchievementsRoute: typeof AchievementsRoute
  AskRoute: typeof AskRoute
  BookingsRoute: typeof BookingsRoute
  ChecklistRoute: typeof ChecklistRoute
  CostRoute: typeof CostRouteWithChildren
  DocumentsRoute: typeof DocumentsRoute
  ItineraryRoute: typeof ItineraryRoute
  MapRoute: typeof MapRoute
  PlanningRoute: typeof PlanningRoute
  SettingsRoute: typeof SettingsRoute
  StoryRoute: typeof StoryRoute
  TravellersRoute: typeof TravellersRoute
  VehicleRoute: typeof VehicleRoute
  ApiPublicHooksBookingRemindersRoute: typeof ApiPublicHooksBookingRemindersRoute
  ApiPublicHooksDailyBadgeRoute: typeof ApiPublicHooksDailyBadgeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask': {
      id: '/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checklist': {
      id: '/checklist'
      path: '/checklist'
      fullPath: '/checklist'
      preLoaderRoute: typeof ChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cost': {
      id: '/cost'
      path: '/cost'
      fullPath: '/cost'
      preLoaderRoute: typeof CostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/itinerary': {
      id: '/itinerary'
      path: '/itinerary'
      fullPath: '/itinerary'
      preLoaderRoute: typeof ItineraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planning': {
      id: '/planning'
      path: '/planning'
      fullPath: '/planning'
      preLoaderRoute: typeof PlanningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story': {
      id: '/story'
      path: '/story'
      fullPath: '/story'
      preLoaderRoute: typeof StoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/travellers': {
      id: '/travellers'
      path: '/travellers'
      fullPath: '/travellers'
      preLoaderRoute: typeof TravellersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicle': {
      id: '/vehicle'
      path: '/vehicle'
      fullPath: '/vehicle'
      preLoaderRoute: typeof VehicleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cost/share/$token': {
      id: '/cost/share/$token'
      path: '/share/$token'
      fullPath: '/cost/share/$token'
      preLoaderRoute: typeof CostShareTokenRouteImport
      parentRoute: typeof CostRoute
    }
    '/api/public/hooks/booking-reminders': {
      id: '/api/public/hooks/booking-reminders'
      path: '/api/public/hooks/booking-reminders'
      fullPath: '/api/public/hooks/booking-reminders'
      preLoaderRoute: typeof ApiPublicHooksBookingRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/daily-badge': {
      id: '/api/public/hooks/daily-badge'
      path: '/api/public/hooks/daily-badge'
      fullPath: '/api/public/hooks/daily-badge'
      preLoaderRoute: typeof ApiPublicHooksDailyBadgeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CostRouteChildren {
  CostShareTokenRoute: typeof CostShareTokenRoute
}

const CostRouteChildren: CostRouteChildren = {
  CostShareTokenRoute: CostShareTokenRoute,
}

const CostRouteWithChildren = CostRoute._addFileChildren(CostRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AchievementsRoute: AchievementsRoute,
  AskRoute: AskRoute,
  BookingsRoute: BookingsRoute,
  ChecklistRoute: ChecklistRoute,
  CostRoute: CostRouteWithChildren,
  DocumentsRoute: DocumentsRoute,
  ItineraryRoute: ItineraryRoute,
  MapRoute: MapRoute,
  PlanningRoute: PlanningRoute,
  SettingsRoute: SettingsRoute,
  StoryRoute: StoryRoute,
  TravellersRoute: TravellersRoute,
  VehicleRoute: VehicleRoute,
  ApiPublicHooksBookingRemindersRoute: ApiPublicHooksBookingRemindersRoute,
  ApiPublicHooksDailyBadgeRoute: ApiPublicHooksDailyBadgeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
